[2024-01-29T21:30:47.631+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: downloading_fundamentals.wait_for_api manual__2024-01-29T21:29:24.129763+00:00 [queued]>
[2024-01-29T21:30:47.640+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: downloading_fundamentals.wait_for_api manual__2024-01-29T21:29:24.129763+00:00 [queued]>
[2024-01-29T21:30:47.640+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 2
[2024-01-29T21:30:47.663+0000] {taskinstance.py:1382} INFO - Executing <Task(HttpSensor): wait_for_api> on 2024-01-29 21:29:24.129763+00:00
[2024-01-29T21:30:47.669+0000] {standard_task_runner.py:57} INFO - Started process 500 to run task
[2024-01-29T21:30:47.673+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'downloading_fundamentals', 'wait_for_api', 'manual__2024-01-29T21:29:24.129763+00:00', '--job-id', '51', '--raw', '--subdir', 'DAGS_FOLDER/fundamental_data_pipeline.py', '--cfg-path', '/tmp/tmpy81vhdir']
[2024-01-29T21:30:47.676+0000] {standard_task_runner.py:85} INFO - Job 51: Subtask wait_for_api
[2024-01-29T21:30:47.728+0000] {task_command.py:416} INFO - Running <TaskInstance: downloading_fundamentals.wait_for_api manual__2024-01-29T21:29:24.129763+00:00 [running]> on host 77ce723575d8
[2024-01-29T21:30:47.820+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='gerardchurch133@gmail.com' AIRFLOW_CTX_DAG_OWNER='Airflow' AIRFLOW_CTX_DAG_ID='downloading_fundamentals' AIRFLOW_CTX_TASK_ID='wait_for_api' AIRFLOW_CTX_EXECUTION_DATE='2024-01-29T21:29:24.129763+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-01-29T21:29:24.129763+00:00'
[2024-01-29T21:30:47.821+0000] {http.py:130} INFO - Poking: symbols/get-financials
[2024-01-29T21:30:47.846+0000] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/sensors/base.py", line 257, in execute
    raise e
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/sensors/base.py", line 239, in execute
    poke_return = self.poke(context)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/http/sensors/http.py", line 148, in poke
    raise exc
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/http/sensors/http.py", line 132, in poke
    response = hook.run(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/http/hooks/http.py", line 145, in run
    session = self.get_conn(headers)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/http/hooks/http.py", line 98, in get_conn
    conn = self.get_connection(self.http_conn_id)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/hooks/base.py", line 72, in get_connection
    conn = Connection.get_connection_from_secrets(conn_id)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/connection.py", line 477, in get_connection_from_secrets
    raise AirflowNotFoundException(f"The conn_id `{conn_id}` isn't defined")
airflow.exceptions.AirflowNotFoundException: The conn_id `rapid_api` isn't defined
[2024-01-29T21:30:47.857+0000] {taskinstance.py:1400} INFO - Marking task as UP_FOR_RETRY. dag_id=downloading_fundamentals, task_id=wait_for_api, execution_date=20240129T212924, start_date=20240129T213047, end_date=20240129T213047
[2024-01-29T21:30:47.892+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 51 for task wait_for_api (The conn_id `rapid_api` isn't defined; 500)
[2024-01-29T21:30:47.927+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2024-01-29T21:30:47.965+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
