[2024-01-31T21:19:39.922+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: calculating_gross_margin.sending_email manual__2024-01-31T21:13:39.901724+00:00 [queued]>
[2024-01-31T21:19:39.933+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: calculating_gross_margin.sending_email manual__2024-01-31T21:13:39.901724+00:00 [queued]>
[2024-01-31T21:19:39.934+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 2
[2024-01-31T21:19:39.951+0000] {taskinstance.py:1382} INFO - Executing <Task(EmailOperator): sending_email> on 2024-01-31 21:13:39.901724+00:00
[2024-01-31T21:19:39.957+0000] {standard_task_runner.py:57} INFO - Started process 474 to run task
[2024-01-31T21:19:39.962+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'calculating_gross_margin', 'sending_email', 'manual__2024-01-31T21:13:39.901724+00:00', '--job-id', '104', '--raw', '--subdir', 'DAGS_FOLDER/fundamental_data_pipeline.py', '--cfg-path', '/tmp/tmp1hr2ix3k']
[2024-01-31T21:19:39.966+0000] {standard_task_runner.py:85} INFO - Job 104: Subtask sending_email
[2024-01-31T21:19:40.088+0000] {task_command.py:416} INFO - Running <TaskInstance: calculating_gross_margin.sending_email manual__2024-01-31T21:13:39.901724+00:00 [running]> on host 66a208939447
[2024-01-31T21:19:40.173+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='gerardchurch133@outlook.com' AIRFLOW_CTX_DAG_OWNER='Airflow' AIRFLOW_CTX_DAG_ID='calculating_gross_margin' AIRFLOW_CTX_TASK_ID='sending_email' AIRFLOW_CTX_EXECUTION_DATE='2024-01-31T21:13:39.901724+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-01-31T21:13:39.901724+00:00'
[2024-01-31T21:19:40.185+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.8/site-packages/***/utils/email.py:154: RemovedInAirflow3Warning: Fetching SMTP credentials from configuration variables will be deprecated in a future release. Please set credentials using a connection instead.
  send_mime_email(e_from=mail_from, e_to=recipients, mime_msg=msg, conn_id=conn_id, dryrun=dryrun)

[2024-01-31T21:19:40.186+0000] {configuration.py:1050} WARNING - section/key [smtp/smtp_user] not found in config
[2024-01-31T21:19:40.186+0000] {email.py:270} INFO - Email alerting: attempt 1
[2024-01-31T21:19:40.188+0000] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/email.py", line 77, in execute
    send_email(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/email.py", line 80, in send_email
    return backend(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/email.py", line 154, in send_email_smtp
    send_mime_email(e_from=mail_from, e_to=recipients, mime_msg=msg, conn_id=conn_id, dryrun=dryrun)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/email.py", line 272, in send_mime_email
    smtp_conn = _get_smtp_connection(smtp_host, smtp_port, smtp_timeout, smtp_ssl)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/email.py", line 316, in _get_smtp_connection
    return smtplib.SMTP(host=host, port=port, timeout=timeout)
  File "/usr/local/lib/python3.8/smtplib.py", line 255, in __init__
    (code, msg) = self.connect(host, port)
  File "/usr/local/lib/python3.8/smtplib.py", line 339, in connect
    self.sock = self._get_socket(host, port, self.timeout)
  File "/usr/local/lib/python3.8/smtplib.py", line 310, in _get_socket
    return socket.create_connection((host, port), timeout,
  File "/usr/local/lib/python3.8/socket.py", line 808, in create_connection
    raise err
  File "/usr/local/lib/python3.8/socket.py", line 796, in create_connection
    sock.connect(sa)
OSError: [Errno 99] Cannot assign requested address
[2024-01-31T21:19:40.198+0000] {taskinstance.py:1400} INFO - Marking task as UP_FOR_RETRY. dag_id=calculating_gross_margin, task_id=sending_email, execution_date=20240131T211339, start_date=20240131T211939, end_date=20240131T211940
[2024-01-31T21:19:40.215+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 104 for task sending_email ([Errno 99] Cannot assign requested address; 474)
[2024-01-31T21:19:40.255+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2024-01-31T21:19:40.274+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
