[2024-01-28T00:42:35.246+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: downloading_fundamentals.downloading_fundamentals scheduled__2024-01-27T00:00:00+00:00 [queued]>
[2024-01-28T00:42:35.259+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: downloading_fundamentals.downloading_fundamentals scheduled__2024-01-27T00:00:00+00:00 [queued]>
[2024-01-28T00:42:35.260+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 2
[2024-01-28T00:42:35.278+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): downloading_fundamentals> on 2024-01-27 00:00:00+00:00
[2024-01-28T00:42:35.295+0000] {standard_task_runner.py:57} INFO - Started process 142 to run task
[2024-01-28T00:42:35.325+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'downloading_fundamentals', 'downloading_fundamentals', 'scheduled__2024-01-27T00:00:00+00:00', '--job-id', '18', '--raw', '--subdir', 'DAGS_FOLDER/fundamental_data_pipeline.py', '--cfg-path', '/tmp/tmpz_v4loyf']
[2024-01-28T00:42:35.369+0000] {standard_task_runner.py:85} INFO - Job 18: Subtask downloading_fundamentals
[2024-01-28T00:42:35.771+0000] {task_command.py:416} INFO - Running <TaskInstance: downloading_fundamentals.downloading_fundamentals scheduled__2024-01-27T00:00:00+00:00 [running]> on host ad2d138ad454
[2024-01-28T00:42:36.016+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='gerardchurch133@gmail.com' AIRFLOW_CTX_DAG_OWNER='Airflow' AIRFLOW_CTX_DAG_ID='downloading_fundamentals' AIRFLOW_CTX_TASK_ID='downloading_fundamentals' AIRFLOW_CTX_EXECUTION_DATE='2024-01-27T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-01-27T00:00:00+00:00'
[2024-01-28T00:42:36.031+0000] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
TypeError: get_fundamental_data() missing 1 required positional argument: 'ticker'
[2024-01-28T00:42:36.110+0000] {taskinstance.py:1400} INFO - Marking task as UP_FOR_RETRY. dag_id=downloading_fundamentals, task_id=downloading_fundamentals, execution_date=20240127T000000, start_date=20240128T004235, end_date=20240128T004236
[2024-01-28T00:42:36.161+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 18 for task downloading_fundamentals (get_fundamental_data() missing 1 required positional argument: 'ticker'; 142)
[2024-01-28T00:42:36.218+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2024-01-28T00:42:36.251+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
