[2023-12-04T22:44:57.589+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: downloading_fundamentals.downloading_fundamentals scheduled__2023-12-03T00:00:00+00:00 [queued]>
[2023-12-04T22:44:57.599+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: downloading_fundamentals.downloading_fundamentals scheduled__2023-12-03T00:00:00+00:00 [queued]>
[2023-12-04T22:44:57.599+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 2
[2023-12-04T22:44:57.613+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): downloading_fundamentals> on 2023-12-03 00:00:00+00:00
[2023-12-04T22:44:57.622+0000] {standard_task_runner.py:57} INFO - Started process 57 to run task
[2023-12-04T22:44:57.626+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'downloading_fundamentals', 'downloading_fundamentals', 'scheduled__2023-12-03T00:00:00+00:00', '--job-id', '18', '--raw', '--subdir', 'DAGS_FOLDER/fundamental_data_pipeline.py', '--cfg-path', '/tmp/tmpm0h7cnlx']
[2023-12-04T22:44:57.629+0000] {standard_task_runner.py:85} INFO - Job 18: Subtask downloading_fundamentals
[2023-12-04T22:44:57.694+0000] {task_command.py:416} INFO - Running <TaskInstance: downloading_fundamentals.downloading_fundamentals scheduled__2023-12-03T00:00:00+00:00 [running]> on host 276b4b7f65b2
[2023-12-04T22:44:58.054+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='gerardchurch133@gmail.com' AIRFLOW_CTX_DAG_OWNER='Airflow' AIRFLOW_CTX_DAG_ID='downloading_fundamentals' AIRFLOW_CTX_TASK_ID='downloading_fundamentals' AIRFLOW_CTX_EXECUTION_DATE='2023-12-03T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-12-03T00:00:00+00:00'
[2023-12-04T22:44:58.056+0000] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/fundamental_data_pipeline.py", line 16, in get_fundemental_data
    headers = {"X-RapidAPI-Key": os.environ['rapidapi_key'],
  File "/usr/local/lib/python3.8/os.py", line 675, in __getitem__
    raise KeyError(key) from None
KeyError: 'rapidapi_key'
[2023-12-04T22:44:58.071+0000] {taskinstance.py:1400} INFO - Marking task as UP_FOR_RETRY. dag_id=downloading_fundamentals, task_id=downloading_fundamentals, execution_date=20231203T000000, start_date=20231204T224457, end_date=20231204T224458
[2023-12-04T22:44:58.091+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 18 for task downloading_fundamentals ('rapidapi_key'; 57)
[2023-12-04T22:44:58.122+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-12-04T22:44:58.139+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
