[2024-01-30T23:14:31.945+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: downloading_fundamentals.sending_email manual__2024-01-30T23:08:30.681308+00:00 [queued]>
[2024-01-30T23:14:31.954+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: downloading_fundamentals.sending_email manual__2024-01-30T23:08:30.681308+00:00 [queued]>
[2024-01-30T23:14:31.955+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 2
[2024-01-30T23:14:31.967+0000] {taskinstance.py:1382} INFO - Executing <Task(EmailOperator): sending_email> on 2024-01-30 23:08:30.681308+00:00
[2024-01-30T23:14:31.974+0000] {standard_task_runner.py:57} INFO - Started process 614 to run task
[2024-01-30T23:14:31.977+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'downloading_fundamentals', 'sending_email', 'manual__2024-01-30T23:08:30.681308+00:00', '--job-id', '80', '--raw', '--subdir', 'DAGS_FOLDER/fundamental_data_pipeline.py', '--cfg-path', '/tmp/tmp5t2xehvh']
[2024-01-30T23:14:31.980+0000] {standard_task_runner.py:85} INFO - Job 80: Subtask sending_email
[2024-01-30T23:14:32.042+0000] {task_command.py:416} INFO - Running <TaskInstance: downloading_fundamentals.sending_email manual__2024-01-30T23:08:30.681308+00:00 [running]> on host f7d0f38ec0f6
[2024-01-30T23:14:32.151+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='gerardchurch133@gmail.com' AIRFLOW_CTX_DAG_OWNER='Airflow' AIRFLOW_CTX_DAG_ID='downloading_fundamentals' AIRFLOW_CTX_TASK_ID='sending_email' AIRFLOW_CTX_EXECUTION_DATE='2024-01-30T23:08:30.681308+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-01-30T23:08:30.681308+00:00'
[2024-01-30T23:14:32.168+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.8/site-packages/***/utils/email.py:154: RemovedInAirflow3Warning: Fetching SMTP credentials from configuration variables will be deprecated in a future release. Please set credentials using a connection instead.
  send_mime_email(e_from=mail_from, e_to=recipients, mime_msg=msg, conn_id=conn_id, dryrun=dryrun)

[2024-01-30T23:14:32.169+0000] {configuration.py:1050} WARNING - section/key [smtp/smtp_user] not found in config
[2024-01-30T23:14:32.170+0000] {email.py:270} INFO - Email alerting: attempt 1
[2024-01-30T23:14:32.172+0000] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/email.py", line 77, in execute
    send_email(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/email.py", line 80, in send_email
    return backend(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/email.py", line 154, in send_email_smtp
    send_mime_email(e_from=mail_from, e_to=recipients, mime_msg=msg, conn_id=conn_id, dryrun=dryrun)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/email.py", line 272, in send_mime_email
    smtp_conn = _get_smtp_connection(smtp_host, smtp_port, smtp_timeout, smtp_ssl)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/email.py", line 316, in _get_smtp_connection
    return smtplib.SMTP(host=host, port=port, timeout=timeout)
  File "/usr/local/lib/python3.8/smtplib.py", line 255, in __init__
    (code, msg) = self.connect(host, port)
  File "/usr/local/lib/python3.8/smtplib.py", line 339, in connect
    self.sock = self._get_socket(host, port, self.timeout)
  File "/usr/local/lib/python3.8/smtplib.py", line 310, in _get_socket
    return socket.create_connection((host, port), timeout,
  File "/usr/local/lib/python3.8/socket.py", line 808, in create_connection
    raise err
  File "/usr/local/lib/python3.8/socket.py", line 796, in create_connection
    sock.connect(sa)
OSError: [Errno 99] Cannot assign requested address
[2024-01-30T23:14:32.183+0000] {taskinstance.py:1400} INFO - Marking task as UP_FOR_RETRY. dag_id=downloading_fundamentals, task_id=sending_email, execution_date=20240130T230830, start_date=20240130T231431, end_date=20240130T231432
[2024-01-30T23:14:32.196+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 80 for task sending_email ([Errno 99] Cannot assign requested address; 614)
[2024-01-30T23:14:32.230+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2024-01-30T23:14:32.249+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
