[2023-12-05T22:13:22.540+0000] {processor.py:157} INFO - Started process (PID=169) to work on /opt/airflow/dags/fundamental_data_pipeline.py
[2023-12-05T22:13:22.551+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/fundamental_data_pipeline.py for tasks to queue
[2023-12-05T22:13:22.704+0000] {logging_mixin.py:154} INFO - [2023-12-05T22:13:22.699+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/fundamental_data_pipeline.py
[2023-12-05T22:13:23.125+0000] {logging_mixin.py:154} INFO - [2023-12-05T22:13:23.063+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/fundamental_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/fundamental_data_pipeline.py", line 11, in <module>
    from libs.financials_api_get import get_fundemental_data
ModuleNotFoundError: No module named 'libs'
[2023-12-05T22:13:23.150+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/fundamental_data_pipeline.py
[2023-12-05T22:13:23.690+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/fundamental_data_pipeline.py took 1.219 seconds
[2023-12-05T22:13:55.409+0000] {processor.py:157} INFO - Started process (PID=177) to work on /opt/airflow/dags/fundamental_data_pipeline.py
[2023-12-05T22:13:55.424+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/fundamental_data_pipeline.py for tasks to queue
[2023-12-05T22:13:55.456+0000] {logging_mixin.py:154} INFO - [2023-12-05T22:13:55.454+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/fundamental_data_pipeline.py
[2023-12-05T22:13:55.626+0000] {logging_mixin.py:154} INFO - [2023-12-05T22:13:55.594+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/fundamental_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/fundamental_data_pipeline.py", line 11, in <module>
    from libs.financials_api_get import get_fundemental_data
ModuleNotFoundError: No module named 'libs'
[2023-12-05T22:13:55.630+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/fundamental_data_pipeline.py
[2023-12-05T22:13:55.817+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/fundamental_data_pipeline.py took 0.474 seconds
[2023-12-05T22:14:26.029+0000] {processor.py:157} INFO - Started process (PID=185) to work on /opt/airflow/dags/fundamental_data_pipeline.py
[2023-12-05T22:14:26.033+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/fundamental_data_pipeline.py for tasks to queue
[2023-12-05T22:14:26.051+0000] {logging_mixin.py:154} INFO - [2023-12-05T22:14:26.050+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/fundamental_data_pipeline.py
[2023-12-05T22:14:26.100+0000] {logging_mixin.py:154} INFO - [2023-12-05T22:14:26.090+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/fundamental_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/fundamental_data_pipeline.py", line 11, in <module>
    from libs.financials_api_get import get_fundemental_data
ModuleNotFoundError: No module named 'libs'
[2023-12-05T22:14:26.102+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/fundamental_data_pipeline.py
[2023-12-05T22:14:26.843+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/fundamental_data_pipeline.py took 0.833 seconds
[2023-12-05T22:14:57.113+0000] {processor.py:157} INFO - Started process (PID=193) to work on /opt/airflow/dags/fundamental_data_pipeline.py
[2023-12-05T22:14:57.115+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/fundamental_data_pipeline.py for tasks to queue
[2023-12-05T22:14:57.121+0000] {logging_mixin.py:154} INFO - [2023-12-05T22:14:57.121+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/fundamental_data_pipeline.py
[2023-12-05T22:14:57.158+0000] {logging_mixin.py:154} INFO - [2023-12-05T22:14:57.151+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/fundamental_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/fundamental_data_pipeline.py", line 11, in <module>
    from libs.financials_api_get import get_fundemental_data
ModuleNotFoundError: No module named 'libs'
[2023-12-05T22:14:57.160+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/fundamental_data_pipeline.py
[2023-12-05T22:14:57.190+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/fundamental_data_pipeline.py took 0.084 seconds
[2023-12-05T22:15:27.397+0000] {processor.py:157} INFO - Started process (PID=201) to work on /opt/airflow/dags/fundamental_data_pipeline.py
[2023-12-05T22:15:27.399+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/fundamental_data_pipeline.py for tasks to queue
[2023-12-05T22:15:27.402+0000] {logging_mixin.py:154} INFO - [2023-12-05T22:15:27.402+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/fundamental_data_pipeline.py
[2023-12-05T22:15:27.434+0000] {logging_mixin.py:154} INFO - [2023-12-05T22:15:27.428+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/fundamental_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/fundamental_data_pipeline.py", line 11, in <module>
    from libs.financials_api_get import get_fundemental_data
ModuleNotFoundError: No module named 'libs'
[2023-12-05T22:15:27.435+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/fundamental_data_pipeline.py
[2023-12-05T22:15:27.458+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/fundamental_data_pipeline.py took 0.064 seconds
[2023-12-05T22:15:57.569+0000] {processor.py:157} INFO - Started process (PID=209) to work on /opt/airflow/dags/fundamental_data_pipeline.py
[2023-12-05T22:15:57.571+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/fundamental_data_pipeline.py for tasks to queue
[2023-12-05T22:15:57.573+0000] {logging_mixin.py:154} INFO - [2023-12-05T22:15:57.573+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/fundamental_data_pipeline.py
[2023-12-05T22:15:57.606+0000] {logging_mixin.py:154} INFO - [2023-12-05T22:15:57.602+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/fundamental_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/fundamental_data_pipeline.py", line 11, in <module>
    from libs.financials_api_get import get_fundemental_data
ModuleNotFoundError: No module named 'libs'
[2023-12-05T22:15:57.609+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/fundamental_data_pipeline.py
[2023-12-05T22:15:57.635+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/fundamental_data_pipeline.py took 0.069 seconds
[2023-12-05T22:16:27.798+0000] {processor.py:157} INFO - Started process (PID=217) to work on /opt/airflow/dags/fundamental_data_pipeline.py
[2023-12-05T22:16:27.799+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/fundamental_data_pipeline.py for tasks to queue
[2023-12-05T22:16:27.801+0000] {logging_mixin.py:154} INFO - [2023-12-05T22:16:27.801+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/fundamental_data_pipeline.py
[2023-12-05T22:16:27.829+0000] {logging_mixin.py:154} INFO - [2023-12-05T22:16:27.822+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/fundamental_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/fundamental_data_pipeline.py", line 11, in <module>
    from libs.financials_api_get import get_fundemental_data
ModuleNotFoundError: No module named 'libs'
[2023-12-05T22:16:27.831+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/fundamental_data_pipeline.py
[2023-12-05T22:16:27.856+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/fundamental_data_pipeline.py took 0.061 seconds
[2023-12-05T22:16:57.991+0000] {processor.py:157} INFO - Started process (PID=225) to work on /opt/airflow/dags/fundamental_data_pipeline.py
[2023-12-05T22:16:57.995+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/fundamental_data_pipeline.py for tasks to queue
[2023-12-05T22:16:57.999+0000] {logging_mixin.py:154} INFO - [2023-12-05T22:16:57.999+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/fundamental_data_pipeline.py
[2023-12-05T22:16:58.039+0000] {logging_mixin.py:154} INFO - [2023-12-05T22:16:58.033+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/fundamental_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/fundamental_data_pipeline.py", line 11, in <module>
    from libs.financials_api_get import get_fundemental_data
ModuleNotFoundError: No module named 'libs'
[2023-12-05T22:16:58.041+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/fundamental_data_pipeline.py
[2023-12-05T22:16:58.066+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/fundamental_data_pipeline.py took 0.079 seconds
[2023-12-05T22:17:28.290+0000] {processor.py:157} INFO - Started process (PID=233) to work on /opt/airflow/dags/fundamental_data_pipeline.py
[2023-12-05T22:17:28.291+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/fundamental_data_pipeline.py for tasks to queue
[2023-12-05T22:17:28.293+0000] {logging_mixin.py:154} INFO - [2023-12-05T22:17:28.293+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/fundamental_data_pipeline.py
[2023-12-05T22:17:28.325+0000] {logging_mixin.py:154} INFO - [2023-12-05T22:17:28.318+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/fundamental_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/fundamental_data_pipeline.py", line 11, in <module>
    from libs.financials_api_get import get_fundemental_data
ModuleNotFoundError: No module named 'libs'
[2023-12-05T22:17:28.326+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/fundamental_data_pipeline.py
[2023-12-05T22:17:28.348+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/fundamental_data_pipeline.py took 0.062 seconds
[2023-12-05T22:17:58.453+0000] {processor.py:157} INFO - Started process (PID=241) to work on /opt/airflow/dags/fundamental_data_pipeline.py
[2023-12-05T22:17:58.455+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/fundamental_data_pipeline.py for tasks to queue
[2023-12-05T22:17:58.458+0000] {logging_mixin.py:154} INFO - [2023-12-05T22:17:58.458+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/fundamental_data_pipeline.py
[2023-12-05T22:17:58.484+0000] {logging_mixin.py:154} INFO - [2023-12-05T22:17:58.480+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/fundamental_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/fundamental_data_pipeline.py", line 11, in <module>
    from libs.financials_api_get import get_fundemental_data
ModuleNotFoundError: No module named 'libs'
[2023-12-05T22:17:58.487+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/fundamental_data_pipeline.py
[2023-12-05T22:17:58.508+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/fundamental_data_pipeline.py took 0.057 seconds
[2023-12-05T22:18:28.811+0000] {processor.py:157} INFO - Started process (PID=249) to work on /opt/airflow/dags/fundamental_data_pipeline.py
[2023-12-05T22:18:28.812+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/fundamental_data_pipeline.py for tasks to queue
[2023-12-05T22:18:28.814+0000] {logging_mixin.py:154} INFO - [2023-12-05T22:18:28.814+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/fundamental_data_pipeline.py
[2023-12-05T22:18:28.843+0000] {logging_mixin.py:154} INFO - [2023-12-05T22:18:28.838+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/fundamental_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/fundamental_data_pipeline.py", line 11, in <module>
    from libs.financials_api_get import get_fundemental_data
ModuleNotFoundError: No module named 'libs'
[2023-12-05T22:18:28.845+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/fundamental_data_pipeline.py
[2023-12-05T22:18:28.871+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/fundamental_data_pipeline.py took 0.063 seconds
[2023-12-05T22:18:58.969+0000] {processor.py:157} INFO - Started process (PID=257) to work on /opt/airflow/dags/fundamental_data_pipeline.py
[2023-12-05T22:18:58.970+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/fundamental_data_pipeline.py for tasks to queue
[2023-12-05T22:18:58.973+0000] {logging_mixin.py:154} INFO - [2023-12-05T22:18:58.973+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/fundamental_data_pipeline.py
[2023-12-05T22:18:58.997+0000] {logging_mixin.py:154} INFO - [2023-12-05T22:18:58.992+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/fundamental_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/fundamental_data_pipeline.py", line 11, in <module>
    from libs.financials_api_get import get_fundemental_data
ModuleNotFoundError: No module named 'libs'
[2023-12-05T22:18:58.999+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/fundamental_data_pipeline.py
[2023-12-05T22:18:59.018+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/fundamental_data_pipeline.py took 0.052 seconds
[2023-12-05T22:19:29.199+0000] {processor.py:157} INFO - Started process (PID=265) to work on /opt/airflow/dags/fundamental_data_pipeline.py
[2023-12-05T22:19:29.200+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/fundamental_data_pipeline.py for tasks to queue
[2023-12-05T22:19:29.203+0000] {logging_mixin.py:154} INFO - [2023-12-05T22:19:29.202+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/fundamental_data_pipeline.py
[2023-12-05T22:19:29.229+0000] {logging_mixin.py:154} INFO - [2023-12-05T22:19:29.224+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/fundamental_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/fundamental_data_pipeline.py", line 11, in <module>
    from libs.financials_api_get import get_fundemental_data
ModuleNotFoundError: No module named 'libs'
[2023-12-05T22:19:29.230+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/fundamental_data_pipeline.py
[2023-12-05T22:19:29.250+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/fundamental_data_pipeline.py took 0.055 seconds
[2023-12-05T22:19:59.373+0000] {processor.py:157} INFO - Started process (PID=273) to work on /opt/airflow/dags/fundamental_data_pipeline.py
[2023-12-05T22:19:59.374+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/fundamental_data_pipeline.py for tasks to queue
[2023-12-05T22:19:59.378+0000] {logging_mixin.py:154} INFO - [2023-12-05T22:19:59.377+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/fundamental_data_pipeline.py
[2023-12-05T22:19:59.401+0000] {logging_mixin.py:154} INFO - [2023-12-05T22:19:59.396+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/fundamental_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/fundamental_data_pipeline.py", line 11, in <module>
    from libs.financials_api_get import get_fundemental_data
ModuleNotFoundError: No module named 'libs'
[2023-12-05T22:19:59.402+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/fundamental_data_pipeline.py
[2023-12-05T22:19:59.422+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/fundamental_data_pipeline.py took 0.052 seconds
[2023-12-05T22:20:29.580+0000] {processor.py:157} INFO - Started process (PID=281) to work on /opt/airflow/dags/fundamental_data_pipeline.py
[2023-12-05T22:20:29.581+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/fundamental_data_pipeline.py for tasks to queue
[2023-12-05T22:20:29.583+0000] {logging_mixin.py:154} INFO - [2023-12-05T22:20:29.583+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/fundamental_data_pipeline.py
[2023-12-05T22:20:29.612+0000] {logging_mixin.py:154} INFO - [2023-12-05T22:20:29.605+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/fundamental_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/fundamental_data_pipeline.py", line 11, in <module>
    from libs.financials_api_get import get_fundemental_data
ModuleNotFoundError: No module named 'libs'
[2023-12-05T22:20:29.613+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/fundamental_data_pipeline.py
[2023-12-05T22:20:29.635+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/fundamental_data_pipeline.py took 0.058 seconds
[2023-12-05T22:20:59.756+0000] {processor.py:157} INFO - Started process (PID=289) to work on /opt/airflow/dags/fundamental_data_pipeline.py
[2023-12-05T22:20:59.757+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/fundamental_data_pipeline.py for tasks to queue
[2023-12-05T22:20:59.760+0000] {logging_mixin.py:154} INFO - [2023-12-05T22:20:59.759+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/fundamental_data_pipeline.py
[2023-12-05T22:20:59.787+0000] {logging_mixin.py:154} INFO - [2023-12-05T22:20:59.781+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/fundamental_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/fundamental_data_pipeline.py", line 11, in <module>
    from libs.financials_api_get import get_fundemental_data
ModuleNotFoundError: No module named 'libs'
[2023-12-05T22:20:59.788+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/fundamental_data_pipeline.py
[2023-12-05T22:20:59.809+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/fundamental_data_pipeline.py took 0.055 seconds
[2023-12-05T22:21:29.959+0000] {processor.py:157} INFO - Started process (PID=297) to work on /opt/airflow/dags/fundamental_data_pipeline.py
[2023-12-05T22:21:29.961+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/fundamental_data_pipeline.py for tasks to queue
[2023-12-05T22:21:29.963+0000] {logging_mixin.py:154} INFO - [2023-12-05T22:21:29.963+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/fundamental_data_pipeline.py
[2023-12-05T22:21:29.988+0000] {logging_mixin.py:154} INFO - [2023-12-05T22:21:29.983+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/fundamental_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/fundamental_data_pipeline.py", line 11, in <module>
    from libs.financials_api_get import get_fundemental_data
ModuleNotFoundError: No module named 'libs'
[2023-12-05T22:21:29.990+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/fundamental_data_pipeline.py
[2023-12-05T22:21:30.009+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/fundamental_data_pipeline.py took 0.053 seconds
[2023-12-05T22:22:00.135+0000] {processor.py:157} INFO - Started process (PID=305) to work on /opt/airflow/dags/fundamental_data_pipeline.py
[2023-12-05T22:22:00.137+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/fundamental_data_pipeline.py for tasks to queue
[2023-12-05T22:22:00.141+0000] {logging_mixin.py:154} INFO - [2023-12-05T22:22:00.140+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/fundamental_data_pipeline.py
[2023-12-05T22:22:00.167+0000] {logging_mixin.py:154} INFO - [2023-12-05T22:22:00.161+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/fundamental_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/fundamental_data_pipeline.py", line 11, in <module>
    from libs.financials_api_get import get_fundemental_data
ModuleNotFoundError: No module named 'libs'
[2023-12-05T22:22:00.169+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/fundamental_data_pipeline.py
[2023-12-05T22:22:00.199+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/fundamental_data_pipeline.py took 0.069 seconds
[2023-12-05T22:22:30.335+0000] {processor.py:157} INFO - Started process (PID=314) to work on /opt/airflow/dags/fundamental_data_pipeline.py
[2023-12-05T22:22:30.337+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/fundamental_data_pipeline.py for tasks to queue
[2023-12-05T22:22:30.341+0000] {logging_mixin.py:154} INFO - [2023-12-05T22:22:30.340+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/fundamental_data_pipeline.py
[2023-12-05T22:22:30.368+0000] {logging_mixin.py:154} INFO - [2023-12-05T22:22:30.363+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/fundamental_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/fundamental_data_pipeline.py", line 11, in <module>
    from libs.financials_api_get import get_fundemental_data
ModuleNotFoundError: No module named 'libs'
[2023-12-05T22:22:30.370+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/fundamental_data_pipeline.py
[2023-12-05T22:22:30.394+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/fundamental_data_pipeline.py took 0.064 seconds
[2023-12-05T22:23:00.526+0000] {processor.py:157} INFO - Started process (PID=322) to work on /opt/airflow/dags/fundamental_data_pipeline.py
[2023-12-05T22:23:00.527+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/fundamental_data_pipeline.py for tasks to queue
[2023-12-05T22:23:00.529+0000] {logging_mixin.py:154} INFO - [2023-12-05T22:23:00.529+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/fundamental_data_pipeline.py
[2023-12-05T22:23:00.554+0000] {logging_mixin.py:154} INFO - [2023-12-05T22:23:00.549+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/fundamental_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/fundamental_data_pipeline.py", line 11, in <module>
    from libs.financials_api_get import get_fundemental_data
ModuleNotFoundError: No module named 'libs'
[2023-12-05T22:23:00.556+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/fundamental_data_pipeline.py
[2023-12-05T22:23:00.575+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/fundamental_data_pipeline.py took 0.051 seconds
[2023-12-05T22:23:30.741+0000] {processor.py:157} INFO - Started process (PID=330) to work on /opt/airflow/dags/fundamental_data_pipeline.py
[2023-12-05T22:23:30.742+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/fundamental_data_pipeline.py for tasks to queue
[2023-12-05T22:23:30.745+0000] {logging_mixin.py:154} INFO - [2023-12-05T22:23:30.745+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/fundamental_data_pipeline.py
[2023-12-05T22:23:30.767+0000] {logging_mixin.py:154} INFO - [2023-12-05T22:23:30.763+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/fundamental_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/fundamental_data_pipeline.py", line 11, in <module>
    from libs.financials_api_get import get_fundemental_data
ModuleNotFoundError: No module named 'libs'
[2023-12-05T22:23:30.768+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/fundamental_data_pipeline.py
[2023-12-05T22:23:30.785+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/fundamental_data_pipeline.py took 0.047 seconds
[2023-12-05T22:24:00.923+0000] {processor.py:157} INFO - Started process (PID=338) to work on /opt/airflow/dags/fundamental_data_pipeline.py
[2023-12-05T22:24:00.925+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/fundamental_data_pipeline.py for tasks to queue
[2023-12-05T22:24:00.930+0000] {logging_mixin.py:154} INFO - [2023-12-05T22:24:00.929+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/fundamental_data_pipeline.py
[2023-12-05T22:24:00.969+0000] {logging_mixin.py:154} INFO - [2023-12-05T22:24:00.963+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/fundamental_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/fundamental_data_pipeline.py", line 11, in <module>
    from libs.financials_api_get import get_fundemental_data
ModuleNotFoundError: No module named 'libs'
[2023-12-05T22:24:00.971+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/fundamental_data_pipeline.py
[2023-12-05T22:24:00.996+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/fundamental_data_pipeline.py took 0.079 seconds
[2023-12-05T22:24:31.119+0000] {processor.py:157} INFO - Started process (PID=346) to work on /opt/airflow/dags/fundamental_data_pipeline.py
[2023-12-05T22:24:31.121+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/fundamental_data_pipeline.py for tasks to queue
[2023-12-05T22:24:31.124+0000] {logging_mixin.py:154} INFO - [2023-12-05T22:24:31.124+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/fundamental_data_pipeline.py
[2023-12-05T22:24:31.158+0000] {logging_mixin.py:154} INFO - [2023-12-05T22:24:31.152+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/fundamental_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/fundamental_data_pipeline.py", line 11, in <module>
    from libs.financials_api_get import get_fundemental_data
ModuleNotFoundError: No module named 'libs'
[2023-12-05T22:24:31.160+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/fundamental_data_pipeline.py
[2023-12-05T22:24:31.193+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/fundamental_data_pipeline.py took 0.078 seconds
[2023-12-05T22:25:01.334+0000] {processor.py:157} INFO - Started process (PID=354) to work on /opt/airflow/dags/fundamental_data_pipeline.py
[2023-12-05T22:25:01.335+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/fundamental_data_pipeline.py for tasks to queue
[2023-12-05T22:25:01.338+0000] {logging_mixin.py:154} INFO - [2023-12-05T22:25:01.338+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/fundamental_data_pipeline.py
[2023-12-05T22:25:01.367+0000] {logging_mixin.py:154} INFO - [2023-12-05T22:25:01.361+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/fundamental_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/fundamental_data_pipeline.py", line 11, in <module>
    from libs.financials_api_get import get_fundemental_data
ModuleNotFoundError: No module named 'libs'
[2023-12-05T22:25:01.369+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/fundamental_data_pipeline.py
[2023-12-05T22:25:01.391+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/fundamental_data_pipeline.py took 0.061 seconds
[2023-12-05T22:25:31.521+0000] {processor.py:157} INFO - Started process (PID=362) to work on /opt/airflow/dags/fundamental_data_pipeline.py
[2023-12-05T22:25:31.523+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/fundamental_data_pipeline.py for tasks to queue
[2023-12-05T22:25:31.527+0000] {logging_mixin.py:154} INFO - [2023-12-05T22:25:31.526+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/fundamental_data_pipeline.py
[2023-12-05T22:25:31.555+0000] {logging_mixin.py:154} INFO - [2023-12-05T22:25:31.549+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/fundamental_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/fundamental_data_pipeline.py", line 11, in <module>
    from libs.financials_api_get import get_fundemental_data
ModuleNotFoundError: No module named 'libs'
[2023-12-05T22:25:31.557+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/fundamental_data_pipeline.py
[2023-12-05T22:25:31.575+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/fundamental_data_pipeline.py took 0.058 seconds
[2023-12-05T22:26:01.713+0000] {processor.py:157} INFO - Started process (PID=370) to work on /opt/airflow/dags/fundamental_data_pipeline.py
[2023-12-05T22:26:01.714+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/fundamental_data_pipeline.py for tasks to queue
[2023-12-05T22:26:01.716+0000] {logging_mixin.py:154} INFO - [2023-12-05T22:26:01.716+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/fundamental_data_pipeline.py
[2023-12-05T22:26:01.742+0000] {logging_mixin.py:154} INFO - [2023-12-05T22:26:01.737+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/fundamental_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/fundamental_data_pipeline.py", line 11, in <module>
    from libs.financials_api_get import get_fundemental_data
ModuleNotFoundError: No module named 'libs'
[2023-12-05T22:26:01.744+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/fundamental_data_pipeline.py
[2023-12-05T22:26:01.762+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/fundamental_data_pipeline.py took 0.053 seconds
[2023-12-05T22:26:31.892+0000] {processor.py:157} INFO - Started process (PID=378) to work on /opt/airflow/dags/fundamental_data_pipeline.py
[2023-12-05T22:26:31.893+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/fundamental_data_pipeline.py for tasks to queue
[2023-12-05T22:26:31.895+0000] {logging_mixin.py:154} INFO - [2023-12-05T22:26:31.895+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/fundamental_data_pipeline.py
[2023-12-05T22:26:31.920+0000] {logging_mixin.py:154} INFO - [2023-12-05T22:26:31.915+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/fundamental_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/fundamental_data_pipeline.py", line 11, in <module>
    from libs.financials_api_get import get_fundemental_data
ModuleNotFoundError: No module named 'libs'
[2023-12-05T22:26:31.921+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/fundamental_data_pipeline.py
[2023-12-05T22:26:31.939+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/fundamental_data_pipeline.py took 0.050 seconds
[2023-12-05T22:27:02.077+0000] {processor.py:157} INFO - Started process (PID=386) to work on /opt/airflow/dags/fundamental_data_pipeline.py
[2023-12-05T22:27:02.078+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/fundamental_data_pipeline.py for tasks to queue
[2023-12-05T22:27:02.081+0000] {logging_mixin.py:154} INFO - [2023-12-05T22:27:02.080+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/fundamental_data_pipeline.py
[2023-12-05T22:27:02.108+0000] {logging_mixin.py:154} INFO - [2023-12-05T22:27:02.102+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/fundamental_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/fundamental_data_pipeline.py", line 11, in <module>
    from libs.financials_api_get import get_fundemental_data
ModuleNotFoundError: No module named 'libs'
[2023-12-05T22:27:02.109+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/fundamental_data_pipeline.py
[2023-12-05T22:27:02.132+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/fundamental_data_pipeline.py took 0.058 seconds
[2023-12-05T22:27:32.262+0000] {processor.py:157} INFO - Started process (PID=394) to work on /opt/airflow/dags/fundamental_data_pipeline.py
[2023-12-05T22:27:32.264+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/fundamental_data_pipeline.py for tasks to queue
[2023-12-05T22:27:32.266+0000] {logging_mixin.py:154} INFO - [2023-12-05T22:27:32.266+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/fundamental_data_pipeline.py
[2023-12-05T22:27:32.294+0000] {logging_mixin.py:154} INFO - [2023-12-05T22:27:32.289+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/fundamental_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/fundamental_data_pipeline.py", line 11, in <module>
    from libs.financials_api_get import get_fundemental_data
ModuleNotFoundError: No module named 'libs'
[2023-12-05T22:27:32.296+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/fundamental_data_pipeline.py
[2023-12-05T22:27:32.316+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/fundamental_data_pipeline.py took 0.058 seconds
[2023-12-05T22:28:02.466+0000] {processor.py:157} INFO - Started process (PID=402) to work on /opt/airflow/dags/fundamental_data_pipeline.py
[2023-12-05T22:28:02.467+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/fundamental_data_pipeline.py for tasks to queue
[2023-12-05T22:28:02.470+0000] {logging_mixin.py:154} INFO - [2023-12-05T22:28:02.469+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/fundamental_data_pipeline.py
[2023-12-05T22:28:02.520+0000] {logging_mixin.py:154} INFO - [2023-12-05T22:28:02.515+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/fundamental_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/fundamental_data_pipeline.py", line 11, in <module>
    from libs.financials_api_get import get_fundemental_data
ModuleNotFoundError: No module named 'libs'
[2023-12-05T22:28:02.521+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/fundamental_data_pipeline.py
[2023-12-05T22:28:02.570+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/fundamental_data_pipeline.py took 0.108 seconds
[2023-12-05T22:28:32.677+0000] {processor.py:157} INFO - Started process (PID=410) to work on /opt/airflow/dags/fundamental_data_pipeline.py
[2023-12-05T22:28:32.679+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/fundamental_data_pipeline.py for tasks to queue
[2023-12-05T22:28:32.682+0000] {logging_mixin.py:154} INFO - [2023-12-05T22:28:32.681+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/fundamental_data_pipeline.py
[2023-12-05T22:28:32.710+0000] {logging_mixin.py:154} INFO - [2023-12-05T22:28:32.705+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/fundamental_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/fundamental_data_pipeline.py", line 11, in <module>
    from libs.financials_api_get import get_fundemental_data
ModuleNotFoundError: No module named 'libs'
[2023-12-05T22:28:32.712+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/fundamental_data_pipeline.py
[2023-12-05T22:28:32.734+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/fundamental_data_pipeline.py took 0.061 seconds
[2023-12-05T22:29:02.937+0000] {processor.py:157} INFO - Started process (PID=417) to work on /opt/airflow/dags/fundamental_data_pipeline.py
[2023-12-05T22:29:02.938+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/fundamental_data_pipeline.py for tasks to queue
[2023-12-05T22:29:02.940+0000] {logging_mixin.py:154} INFO - [2023-12-05T22:29:02.940+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/fundamental_data_pipeline.py
[2023-12-05T22:29:02.966+0000] {logging_mixin.py:154} INFO - [2023-12-05T22:29:02.961+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/fundamental_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/fundamental_data_pipeline.py", line 11, in <module>
    from libs.financials_api_get import get_fundemental_data
ModuleNotFoundError: No module named 'libs'
[2023-12-05T22:29:02.967+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/fundamental_data_pipeline.py
[2023-12-05T22:29:03.011+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/fundamental_data_pipeline.py took 0.077 seconds
[2023-12-05T22:29:33.118+0000] {processor.py:157} INFO - Started process (PID=425) to work on /opt/airflow/dags/fundamental_data_pipeline.py
[2023-12-05T22:29:33.121+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/fundamental_data_pipeline.py for tasks to queue
[2023-12-05T22:29:33.124+0000] {logging_mixin.py:154} INFO - [2023-12-05T22:29:33.124+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/fundamental_data_pipeline.py
[2023-12-05T22:29:33.148+0000] {logging_mixin.py:154} INFO - [2023-12-05T22:29:33.143+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/fundamental_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/fundamental_data_pipeline.py", line 11, in <module>
    from libs.financials_api_get import get_fundemental_data
ModuleNotFoundError: No module named 'libs'
[2023-12-05T22:29:33.149+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/fundamental_data_pipeline.py
[2023-12-05T22:29:33.170+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/fundamental_data_pipeline.py took 0.056 seconds
[2023-12-05T22:30:03.336+0000] {processor.py:157} INFO - Started process (PID=433) to work on /opt/airflow/dags/fundamental_data_pipeline.py
[2023-12-05T22:30:03.337+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/fundamental_data_pipeline.py for tasks to queue
[2023-12-05T22:30:03.339+0000] {logging_mixin.py:154} INFO - [2023-12-05T22:30:03.339+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/fundamental_data_pipeline.py
[2023-12-05T22:30:03.357+0000] {logging_mixin.py:154} INFO - [2023-12-05T22:30:03.353+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/fundamental_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/fundamental_data_pipeline.py", line 11, in <module>
    from libs.financials_api_get import get_fundemental_data
ModuleNotFoundError: No module named 'libs'
[2023-12-05T22:30:03.358+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/fundamental_data_pipeline.py
[2023-12-05T22:30:03.374+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/fundamental_data_pipeline.py took 0.041 seconds
[2023-12-05T22:30:33.513+0000] {processor.py:157} INFO - Started process (PID=441) to work on /opt/airflow/dags/fundamental_data_pipeline.py
[2023-12-05T22:30:33.514+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/fundamental_data_pipeline.py for tasks to queue
[2023-12-05T22:30:33.516+0000] {logging_mixin.py:154} INFO - [2023-12-05T22:30:33.516+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/fundamental_data_pipeline.py
[2023-12-05T22:30:33.536+0000] {logging_mixin.py:154} INFO - [2023-12-05T22:30:33.533+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/fundamental_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/fundamental_data_pipeline.py", line 11, in <module>
    from libs.financials_api_get import get_fundemental_data
ModuleNotFoundError: No module named 'libs'
[2023-12-05T22:30:33.538+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/fundamental_data_pipeline.py
[2023-12-05T22:30:33.556+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/fundamental_data_pipeline.py took 0.046 seconds
[2023-12-05T22:31:03.680+0000] {processor.py:157} INFO - Started process (PID=449) to work on /opt/airflow/dags/fundamental_data_pipeline.py
[2023-12-05T22:31:03.681+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/fundamental_data_pipeline.py for tasks to queue
[2023-12-05T22:31:03.684+0000] {logging_mixin.py:154} INFO - [2023-12-05T22:31:03.684+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/fundamental_data_pipeline.py
[2023-12-05T22:31:03.707+0000] {logging_mixin.py:154} INFO - [2023-12-05T22:31:03.702+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/fundamental_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/fundamental_data_pipeline.py", line 11, in <module>
    from libs.financials_api_get import get_fundemental_data
ModuleNotFoundError: No module named 'libs'
[2023-12-05T22:31:03.709+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/fundamental_data_pipeline.py
[2023-12-05T22:31:03.727+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/fundamental_data_pipeline.py took 0.050 seconds
[2023-12-05T22:31:33.850+0000] {processor.py:157} INFO - Started process (PID=457) to work on /opt/airflow/dags/fundamental_data_pipeline.py
[2023-12-05T22:31:33.851+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/fundamental_data_pipeline.py for tasks to queue
[2023-12-05T22:31:33.854+0000] {logging_mixin.py:154} INFO - [2023-12-05T22:31:33.854+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/fundamental_data_pipeline.py
[2023-12-05T22:31:33.875+0000] {logging_mixin.py:154} INFO - [2023-12-05T22:31:33.872+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/fundamental_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/fundamental_data_pipeline.py", line 11, in <module>
    from libs.financials_api_get import get_fundemental_data
ModuleNotFoundError: No module named 'libs'
[2023-12-05T22:31:33.877+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/fundamental_data_pipeline.py
[2023-12-05T22:31:33.895+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/fundamental_data_pipeline.py took 0.049 seconds
[2023-12-05T22:32:04.033+0000] {processor.py:157} INFO - Started process (PID=465) to work on /opt/airflow/dags/fundamental_data_pipeline.py
[2023-12-05T22:32:04.034+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/fundamental_data_pipeline.py for tasks to queue
[2023-12-05T22:32:04.036+0000] {logging_mixin.py:154} INFO - [2023-12-05T22:32:04.036+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/fundamental_data_pipeline.py
[2023-12-05T22:32:04.058+0000] {logging_mixin.py:154} INFO - [2023-12-05T22:32:04.054+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/fundamental_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/fundamental_data_pipeline.py", line 11, in <module>
    from libs.financials_api_get import get_fundemental_data
ModuleNotFoundError: No module named 'libs'
[2023-12-05T22:32:04.059+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/fundamental_data_pipeline.py
[2023-12-05T22:32:04.077+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/fundamental_data_pipeline.py took 0.047 seconds
[2023-12-05T22:32:34.211+0000] {processor.py:157} INFO - Started process (PID=473) to work on /opt/airflow/dags/fundamental_data_pipeline.py
[2023-12-05T22:32:34.213+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/fundamental_data_pipeline.py for tasks to queue
[2023-12-05T22:32:34.215+0000] {logging_mixin.py:154} INFO - [2023-12-05T22:32:34.215+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/fundamental_data_pipeline.py
[2023-12-05T22:32:34.235+0000] {logging_mixin.py:154} INFO - [2023-12-05T22:32:34.231+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/fundamental_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/fundamental_data_pipeline.py", line 11, in <module>
    from libs.financials_api_get import get_fundemental_data
ModuleNotFoundError: No module named 'libs'
[2023-12-05T22:32:34.237+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/fundamental_data_pipeline.py
[2023-12-05T22:32:34.254+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/fundamental_data_pipeline.py took 0.046 seconds
[2023-12-05T22:33:04.385+0000] {processor.py:157} INFO - Started process (PID=481) to work on /opt/airflow/dags/fundamental_data_pipeline.py
[2023-12-05T22:33:04.386+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/fundamental_data_pipeline.py for tasks to queue
[2023-12-05T22:33:04.389+0000] {logging_mixin.py:154} INFO - [2023-12-05T22:33:04.389+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/fundamental_data_pipeline.py
[2023-12-05T22:33:04.411+0000] {logging_mixin.py:154} INFO - [2023-12-05T22:33:04.407+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/fundamental_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/fundamental_data_pipeline.py", line 11, in <module>
    from libs.financials_api_get import get_fundemental_data
ModuleNotFoundError: No module named 'libs'
[2023-12-05T22:33:04.412+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/fundamental_data_pipeline.py
[2023-12-05T22:33:04.435+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/fundamental_data_pipeline.py took 0.052 seconds
[2023-12-05T22:33:34.595+0000] {processor.py:157} INFO - Started process (PID=489) to work on /opt/airflow/dags/fundamental_data_pipeline.py
[2023-12-05T22:33:34.596+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/fundamental_data_pipeline.py for tasks to queue
[2023-12-05T22:33:34.599+0000] {logging_mixin.py:154} INFO - [2023-12-05T22:33:34.598+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/fundamental_data_pipeline.py
[2023-12-05T22:33:34.646+0000] {logging_mixin.py:154} INFO - [2023-12-05T22:33:34.636+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/fundamental_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/fundamental_data_pipeline.py", line 11, in <module>
    from libs.financials_api_get import get_fundemental_data
ModuleNotFoundError: No module named 'libs'
[2023-12-05T22:33:34.648+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/fundamental_data_pipeline.py
[2023-12-05T22:33:34.702+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/fundamental_data_pipeline.py took 0.110 seconds
[2023-12-05T22:34:04.754+0000] {processor.py:157} INFO - Started process (PID=497) to work on /opt/airflow/dags/fundamental_data_pipeline.py
[2023-12-05T22:34:04.755+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/fundamental_data_pipeline.py for tasks to queue
[2023-12-05T22:34:04.758+0000] {logging_mixin.py:154} INFO - [2023-12-05T22:34:04.758+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/fundamental_data_pipeline.py
[2023-12-05T22:34:04.781+0000] {logging_mixin.py:154} INFO - [2023-12-05T22:34:04.776+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/fundamental_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/fundamental_data_pipeline.py", line 11, in <module>
    from libs.financials_api_get import get_fundemental_data
ModuleNotFoundError: No module named 'libs'
[2023-12-05T22:34:04.783+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/fundamental_data_pipeline.py
[2023-12-05T22:34:04.807+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/fundamental_data_pipeline.py took 0.060 seconds
[2023-12-05T22:34:34.899+0000] {processor.py:157} INFO - Started process (PID=505) to work on /opt/airflow/dags/fundamental_data_pipeline.py
[2023-12-05T22:34:34.900+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/fundamental_data_pipeline.py for tasks to queue
[2023-12-05T22:34:34.902+0000] {logging_mixin.py:154} INFO - [2023-12-05T22:34:34.902+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/fundamental_data_pipeline.py
[2023-12-05T22:34:34.925+0000] {logging_mixin.py:154} INFO - [2023-12-05T22:34:34.921+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/fundamental_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/fundamental_data_pipeline.py", line 11, in <module>
    from libs.financials_api_get import get_fundemental_data
ModuleNotFoundError: No module named 'libs'
[2023-12-05T22:34:34.926+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/fundamental_data_pipeline.py
[2023-12-05T22:34:34.944+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/fundamental_data_pipeline.py took 0.048 seconds
[2023-12-05T22:35:05.120+0000] {processor.py:157} INFO - Started process (PID=513) to work on /opt/airflow/dags/fundamental_data_pipeline.py
[2023-12-05T22:35:05.121+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/fundamental_data_pipeline.py for tasks to queue
[2023-12-05T22:35:05.124+0000] {logging_mixin.py:154} INFO - [2023-12-05T22:35:05.124+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/fundamental_data_pipeline.py
[2023-12-05T22:35:05.155+0000] {logging_mixin.py:154} INFO - [2023-12-05T22:35:05.149+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/fundamental_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/fundamental_data_pipeline.py", line 11, in <module>
    from libs.financials_api_get import get_fundemental_data
ModuleNotFoundError: No module named 'libs'
[2023-12-05T22:35:05.157+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/fundamental_data_pipeline.py
[2023-12-05T22:35:05.182+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/fundamental_data_pipeline.py took 0.064 seconds
[2023-12-05T22:35:35.299+0000] {processor.py:157} INFO - Started process (PID=521) to work on /opt/airflow/dags/fundamental_data_pipeline.py
[2023-12-05T22:35:35.300+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/fundamental_data_pipeline.py for tasks to queue
[2023-12-05T22:35:35.302+0000] {logging_mixin.py:154} INFO - [2023-12-05T22:35:35.302+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/fundamental_data_pipeline.py
[2023-12-05T22:35:35.327+0000] {logging_mixin.py:154} INFO - [2023-12-05T22:35:35.322+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/fundamental_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/fundamental_data_pipeline.py", line 11, in <module>
    from libs.financials_api_get import get_fundemental_data
ModuleNotFoundError: No module named 'libs'
[2023-12-05T22:35:35.328+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/fundamental_data_pipeline.py
[2023-12-05T22:35:35.346+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/fundamental_data_pipeline.py took 0.050 seconds
[2023-12-05T22:36:05.495+0000] {processor.py:157} INFO - Started process (PID=529) to work on /opt/airflow/dags/fundamental_data_pipeline.py
[2023-12-05T22:36:05.496+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/fundamental_data_pipeline.py for tasks to queue
[2023-12-05T22:36:05.499+0000] {logging_mixin.py:154} INFO - [2023-12-05T22:36:05.499+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/fundamental_data_pipeline.py
[2023-12-05T22:36:05.525+0000] {logging_mixin.py:154} INFO - [2023-12-05T22:36:05.520+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/fundamental_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/fundamental_data_pipeline.py", line 11, in <module>
    from libs.financials_api_get import get_fundemental_data
ModuleNotFoundError: No module named 'libs'
[2023-12-05T22:36:05.526+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/fundamental_data_pipeline.py
[2023-12-05T22:36:05.545+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/fundamental_data_pipeline.py took 0.056 seconds
[2023-12-05T22:36:35.662+0000] {processor.py:157} INFO - Started process (PID=537) to work on /opt/airflow/dags/fundamental_data_pipeline.py
[2023-12-05T22:36:35.665+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/fundamental_data_pipeline.py for tasks to queue
[2023-12-05T22:36:35.668+0000] {logging_mixin.py:154} INFO - [2023-12-05T22:36:35.667+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/fundamental_data_pipeline.py
[2023-12-05T22:36:35.694+0000] {logging_mixin.py:154} INFO - [2023-12-05T22:36:35.690+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/fundamental_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/fundamental_data_pipeline.py", line 11, in <module>
    from libs.financials_api_get import get_fundemental_data
ModuleNotFoundError: No module named 'libs'
[2023-12-05T22:36:35.695+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/fundamental_data_pipeline.py
[2023-12-05T22:36:35.712+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/fundamental_data_pipeline.py took 0.053 seconds
[2023-12-05T22:37:05.854+0000] {processor.py:157} INFO - Started process (PID=545) to work on /opt/airflow/dags/fundamental_data_pipeline.py
[2023-12-05T22:37:05.855+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/fundamental_data_pipeline.py for tasks to queue
[2023-12-05T22:37:05.858+0000] {logging_mixin.py:154} INFO - [2023-12-05T22:37:05.858+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/fundamental_data_pipeline.py
[2023-12-05T22:37:05.882+0000] {logging_mixin.py:154} INFO - [2023-12-05T22:37:05.877+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/fundamental_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/fundamental_data_pipeline.py", line 11, in <module>
    from libs.financials_api_get import get_fundemental_data
ModuleNotFoundError: No module named 'libs'
[2023-12-05T22:37:05.883+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/fundamental_data_pipeline.py
[2023-12-05T22:37:05.900+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/fundamental_data_pipeline.py took 0.049 seconds
[2023-12-05T22:37:36.033+0000] {processor.py:157} INFO - Started process (PID=553) to work on /opt/airflow/dags/fundamental_data_pipeline.py
[2023-12-05T22:37:36.034+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/fundamental_data_pipeline.py for tasks to queue
[2023-12-05T22:37:36.037+0000] {logging_mixin.py:154} INFO - [2023-12-05T22:37:36.037+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/fundamental_data_pipeline.py
[2023-12-05T22:37:36.059+0000] {logging_mixin.py:154} INFO - [2023-12-05T22:37:36.055+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/fundamental_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/fundamental_data_pipeline.py", line 11, in <module>
    from libs.financials_api_get import get_fundemental_data
ModuleNotFoundError: No module named 'libs'
[2023-12-05T22:37:36.061+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/fundamental_data_pipeline.py
[2023-12-05T22:37:36.078+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/fundamental_data_pipeline.py took 0.047 seconds
[2023-12-05T22:38:06.206+0000] {processor.py:157} INFO - Started process (PID=561) to work on /opt/airflow/dags/fundamental_data_pipeline.py
[2023-12-05T22:38:06.207+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/fundamental_data_pipeline.py for tasks to queue
[2023-12-05T22:38:06.210+0000] {logging_mixin.py:154} INFO - [2023-12-05T22:38:06.210+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/fundamental_data_pipeline.py
[2023-12-05T22:38:06.231+0000] {logging_mixin.py:154} INFO - [2023-12-05T22:38:06.227+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/fundamental_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/fundamental_data_pipeline.py", line 11, in <module>
    from libs.financials_api_get import get_fundemental_data
ModuleNotFoundError: No module named 'libs'
[2023-12-05T22:38:06.232+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/fundamental_data_pipeline.py
[2023-12-05T22:38:06.281+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/fundamental_data_pipeline.py took 0.078 seconds
[2023-12-05T22:38:36.410+0000] {processor.py:157} INFO - Started process (PID=569) to work on /opt/airflow/dags/fundamental_data_pipeline.py
[2023-12-05T22:38:36.411+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/fundamental_data_pipeline.py for tasks to queue
[2023-12-05T22:38:36.413+0000] {logging_mixin.py:154} INFO - [2023-12-05T22:38:36.413+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/fundamental_data_pipeline.py
[2023-12-05T22:38:36.433+0000] {logging_mixin.py:154} INFO - [2023-12-05T22:38:36.430+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/fundamental_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/fundamental_data_pipeline.py", line 11, in <module>
    from libs.financials_api_get import get_fundemental_data
ModuleNotFoundError: No module named 'libs'
[2023-12-05T22:38:36.434+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/fundamental_data_pipeline.py
[2023-12-05T22:38:36.453+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/fundamental_data_pipeline.py took 0.046 seconds
[2023-12-05T22:39:06.582+0000] {processor.py:157} INFO - Started process (PID=577) to work on /opt/airflow/dags/fundamental_data_pipeline.py
[2023-12-05T22:39:06.583+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/fundamental_data_pipeline.py for tasks to queue
[2023-12-05T22:39:06.586+0000] {logging_mixin.py:154} INFO - [2023-12-05T22:39:06.586+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/fundamental_data_pipeline.py
[2023-12-05T22:39:06.607+0000] {logging_mixin.py:154} INFO - [2023-12-05T22:39:06.603+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/fundamental_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/fundamental_data_pipeline.py", line 11, in <module>
    from libs.financials_api_get import get_fundemental_data
ModuleNotFoundError: No module named 'libs'
[2023-12-05T22:39:06.608+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/fundamental_data_pipeline.py
[2023-12-05T22:39:06.626+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/fundamental_data_pipeline.py took 0.047 seconds
[2023-12-05T22:39:36.771+0000] {processor.py:157} INFO - Started process (PID=585) to work on /opt/airflow/dags/fundamental_data_pipeline.py
[2023-12-05T22:39:36.772+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/fundamental_data_pipeline.py for tasks to queue
[2023-12-05T22:39:36.774+0000] {logging_mixin.py:154} INFO - [2023-12-05T22:39:36.774+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/fundamental_data_pipeline.py
[2023-12-05T22:39:36.800+0000] {logging_mixin.py:154} INFO - [2023-12-05T22:39:36.796+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/fundamental_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/fundamental_data_pipeline.py", line 11, in <module>
    from libs.financials_api_get import get_fundemental_data
ModuleNotFoundError: No module named 'libs'
[2023-12-05T22:39:36.802+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/fundamental_data_pipeline.py
[2023-12-05T22:39:36.819+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/fundamental_data_pipeline.py took 0.051 seconds
[2023-12-05T22:40:06.941+0000] {processor.py:157} INFO - Started process (PID=593) to work on /opt/airflow/dags/fundamental_data_pipeline.py
[2023-12-05T22:40:06.943+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/fundamental_data_pipeline.py for tasks to queue
[2023-12-05T22:40:06.946+0000] {logging_mixin.py:154} INFO - [2023-12-05T22:40:06.945+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/fundamental_data_pipeline.py
[2023-12-05T22:40:06.970+0000] {logging_mixin.py:154} INFO - [2023-12-05T22:40:06.965+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/fundamental_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/fundamental_data_pipeline.py", line 11, in <module>
    from libs.financials_api_get import get_fundemental_data
ModuleNotFoundError: No module named 'libs'
[2023-12-05T22:40:06.971+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/fundamental_data_pipeline.py
[2023-12-05T22:40:06.989+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/fundamental_data_pipeline.py took 0.055 seconds
[2023-12-05T22:40:37.122+0000] {processor.py:157} INFO - Started process (PID=601) to work on /opt/airflow/dags/fundamental_data_pipeline.py
[2023-12-05T22:40:37.123+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/fundamental_data_pipeline.py for tasks to queue
[2023-12-05T22:40:37.125+0000] {logging_mixin.py:154} INFO - [2023-12-05T22:40:37.125+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/fundamental_data_pipeline.py
[2023-12-05T22:40:37.148+0000] {logging_mixin.py:154} INFO - [2023-12-05T22:40:37.144+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/fundamental_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/fundamental_data_pipeline.py", line 11, in <module>
    from libs.financials_api_get import get_fundemental_data
ModuleNotFoundError: No module named 'libs'
[2023-12-05T22:40:37.149+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/fundamental_data_pipeline.py
[2023-12-05T22:40:37.171+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/fundamental_data_pipeline.py took 0.052 seconds
[2023-12-05T22:41:07.298+0000] {processor.py:157} INFO - Started process (PID=609) to work on /opt/airflow/dags/fundamental_data_pipeline.py
[2023-12-05T22:41:07.299+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/fundamental_data_pipeline.py for tasks to queue
[2023-12-05T22:41:07.302+0000] {logging_mixin.py:154} INFO - [2023-12-05T22:41:07.301+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/fundamental_data_pipeline.py
[2023-12-05T22:41:07.322+0000] {logging_mixin.py:154} INFO - [2023-12-05T22:41:07.318+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/fundamental_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/fundamental_data_pipeline.py", line 11, in <module>
    from libs.financials_api_get import get_fundemental_data
ModuleNotFoundError: No module named 'libs'
[2023-12-05T22:41:07.323+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/fundamental_data_pipeline.py
[2023-12-05T22:41:07.340+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/fundamental_data_pipeline.py took 0.045 seconds
[2023-12-05T22:41:37.487+0000] {processor.py:157} INFO - Started process (PID=617) to work on /opt/airflow/dags/fundamental_data_pipeline.py
[2023-12-05T22:41:37.488+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/fundamental_data_pipeline.py for tasks to queue
[2023-12-05T22:41:37.490+0000] {logging_mixin.py:154} INFO - [2023-12-05T22:41:37.490+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/fundamental_data_pipeline.py
[2023-12-05T22:41:37.514+0000] {logging_mixin.py:154} INFO - [2023-12-05T22:41:37.510+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/fundamental_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/fundamental_data_pipeline.py", line 11, in <module>
    from libs.financials_api_get import get_fundemental_data
ModuleNotFoundError: No module named 'libs'
[2023-12-05T22:41:37.516+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/fundamental_data_pipeline.py
[2023-12-05T22:41:37.532+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/fundamental_data_pipeline.py took 0.048 seconds
[2023-12-05T22:42:07.652+0000] {processor.py:157} INFO - Started process (PID=625) to work on /opt/airflow/dags/fundamental_data_pipeline.py
[2023-12-05T22:42:07.653+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/fundamental_data_pipeline.py for tasks to queue
[2023-12-05T22:42:07.656+0000] {logging_mixin.py:154} INFO - [2023-12-05T22:42:07.656+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/fundamental_data_pipeline.py
[2023-12-05T22:42:07.677+0000] {logging_mixin.py:154} INFO - [2023-12-05T22:42:07.673+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/fundamental_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/fundamental_data_pipeline.py", line 11, in <module>
    from libs.financials_api_get import get_fundemental_data
ModuleNotFoundError: No module named 'libs'
[2023-12-05T22:42:07.678+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/fundamental_data_pipeline.py
[2023-12-05T22:42:07.700+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/fundamental_data_pipeline.py took 0.050 seconds
[2023-12-05T22:42:37.838+0000] {processor.py:157} INFO - Started process (PID=633) to work on /opt/airflow/dags/fundamental_data_pipeline.py
[2023-12-05T22:42:37.839+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/fundamental_data_pipeline.py for tasks to queue
[2023-12-05T22:42:37.841+0000] {logging_mixin.py:154} INFO - [2023-12-05T22:42:37.841+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/fundamental_data_pipeline.py
[2023-12-05T22:42:37.865+0000] {logging_mixin.py:154} INFO - [2023-12-05T22:42:37.860+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/fundamental_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/fundamental_data_pipeline.py", line 11, in <module>
    from libs.financials_api_get import get_fundemental_data
ModuleNotFoundError: No module named 'libs'
[2023-12-05T22:42:37.866+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/fundamental_data_pipeline.py
[2023-12-05T22:42:37.884+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/fundamental_data_pipeline.py took 0.049 seconds
[2023-12-05T22:43:08.010+0000] {processor.py:157} INFO - Started process (PID=641) to work on /opt/airflow/dags/fundamental_data_pipeline.py
[2023-12-05T22:43:08.011+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/fundamental_data_pipeline.py for tasks to queue
[2023-12-05T22:43:08.014+0000] {logging_mixin.py:154} INFO - [2023-12-05T22:43:08.014+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/fundamental_data_pipeline.py
[2023-12-05T22:43:08.037+0000] {logging_mixin.py:154} INFO - [2023-12-05T22:43:08.032+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/fundamental_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/fundamental_data_pipeline.py", line 11, in <module>
    from libs.financials_api_get import get_fundemental_data
ModuleNotFoundError: No module named 'libs'
[2023-12-05T22:43:08.039+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/fundamental_data_pipeline.py
[2023-12-05T22:43:08.055+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/fundamental_data_pipeline.py took 0.048 seconds
[2023-12-05T22:43:38.274+0000] {processor.py:157} INFO - Started process (PID=649) to work on /opt/airflow/dags/fundamental_data_pipeline.py
[2023-12-05T22:43:38.275+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/fundamental_data_pipeline.py for tasks to queue
[2023-12-05T22:43:38.277+0000] {logging_mixin.py:154} INFO - [2023-12-05T22:43:38.277+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/fundamental_data_pipeline.py
[2023-12-05T22:43:38.311+0000] {logging_mixin.py:154} INFO - [2023-12-05T22:43:38.306+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/fundamental_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/fundamental_data_pipeline.py", line 11, in <module>
    from libs.financials_api_get import get_fundemental_data
ModuleNotFoundError: No module named 'libs'
[2023-12-05T22:43:38.312+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/fundamental_data_pipeline.py
[2023-12-05T22:43:38.335+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/fundamental_data_pipeline.py took 0.074 seconds
[2023-12-05T22:44:08.424+0000] {processor.py:157} INFO - Started process (PID=657) to work on /opt/airflow/dags/fundamental_data_pipeline.py
[2023-12-05T22:44:08.425+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/fundamental_data_pipeline.py for tasks to queue
[2023-12-05T22:44:08.427+0000] {logging_mixin.py:154} INFO - [2023-12-05T22:44:08.427+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/fundamental_data_pipeline.py
[2023-12-05T22:44:08.446+0000] {logging_mixin.py:154} INFO - [2023-12-05T22:44:08.443+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/fundamental_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/fundamental_data_pipeline.py", line 11, in <module>
    from libs.financials_api_get import get_fundemental_data
ModuleNotFoundError: No module named 'libs'
[2023-12-05T22:44:08.447+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/fundamental_data_pipeline.py
[2023-12-05T22:44:08.466+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/fundamental_data_pipeline.py took 0.045 seconds
[2023-12-05T22:44:38.638+0000] {processor.py:157} INFO - Started process (PID=665) to work on /opt/airflow/dags/fundamental_data_pipeline.py
[2023-12-05T22:44:38.639+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/fundamental_data_pipeline.py for tasks to queue
[2023-12-05T22:44:38.641+0000] {logging_mixin.py:154} INFO - [2023-12-05T22:44:38.641+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/fundamental_data_pipeline.py
[2023-12-05T22:44:38.668+0000] {logging_mixin.py:154} INFO - [2023-12-05T22:44:38.663+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/fundamental_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/fundamental_data_pipeline.py", line 11, in <module>
    from libs.financials_api_get import get_fundemental_data
ModuleNotFoundError: No module named 'libs'
[2023-12-05T22:44:38.670+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/fundamental_data_pipeline.py
[2023-12-05T22:44:38.691+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/fundamental_data_pipeline.py took 0.056 seconds
[2023-12-05T22:45:08.798+0000] {processor.py:157} INFO - Started process (PID=673) to work on /opt/airflow/dags/fundamental_data_pipeline.py
[2023-12-05T22:45:08.799+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/fundamental_data_pipeline.py for tasks to queue
[2023-12-05T22:45:08.802+0000] {logging_mixin.py:154} INFO - [2023-12-05T22:45:08.801+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/fundamental_data_pipeline.py
[2023-12-05T22:45:08.821+0000] {logging_mixin.py:154} INFO - [2023-12-05T22:45:08.817+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/fundamental_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/fundamental_data_pipeline.py", line 11, in <module>
    from libs.financials_api_get import get_fundemental_data
ModuleNotFoundError: No module named 'libs'
[2023-12-05T22:45:08.822+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/fundamental_data_pipeline.py
[2023-12-05T22:45:08.838+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/fundamental_data_pipeline.py took 0.043 seconds
[2023-12-05T22:45:39.005+0000] {processor.py:157} INFO - Started process (PID=681) to work on /opt/airflow/dags/fundamental_data_pipeline.py
[2023-12-05T22:45:39.006+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/fundamental_data_pipeline.py for tasks to queue
[2023-12-05T22:45:39.009+0000] {logging_mixin.py:154} INFO - [2023-12-05T22:45:39.009+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/fundamental_data_pipeline.py
[2023-12-05T22:45:39.035+0000] {logging_mixin.py:154} INFO - [2023-12-05T22:45:39.030+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/fundamental_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/fundamental_data_pipeline.py", line 11, in <module>
    from libs.financials_api_get import get_fundemental_data
ModuleNotFoundError: No module named 'libs'
[2023-12-05T22:45:39.036+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/fundamental_data_pipeline.py
[2023-12-05T22:45:39.055+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/fundamental_data_pipeline.py took 0.052 seconds
[2023-12-05T22:46:09.173+0000] {processor.py:157} INFO - Started process (PID=689) to work on /opt/airflow/dags/fundamental_data_pipeline.py
[2023-12-05T22:46:09.174+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/fundamental_data_pipeline.py for tasks to queue
[2023-12-05T22:46:09.176+0000] {logging_mixin.py:154} INFO - [2023-12-05T22:46:09.176+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/fundamental_data_pipeline.py
[2023-12-05T22:46:09.202+0000] {logging_mixin.py:154} INFO - [2023-12-05T22:46:09.197+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/fundamental_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/fundamental_data_pipeline.py", line 11, in <module>
    from libs.financials_api_get import get_fundemental_data
ModuleNotFoundError: No module named 'libs'
[2023-12-05T22:46:09.203+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/fundamental_data_pipeline.py
[2023-12-05T22:46:09.228+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/fundamental_data_pipeline.py took 0.059 seconds
[2023-12-05T22:46:39.362+0000] {processor.py:157} INFO - Started process (PID=697) to work on /opt/airflow/dags/fundamental_data_pipeline.py
[2023-12-05T22:46:39.363+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/fundamental_data_pipeline.py for tasks to queue
[2023-12-05T22:46:39.365+0000] {logging_mixin.py:154} INFO - [2023-12-05T22:46:39.365+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/fundamental_data_pipeline.py
[2023-12-05T22:46:39.387+0000] {logging_mixin.py:154} INFO - [2023-12-05T22:46:39.382+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/fundamental_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/fundamental_data_pipeline.py", line 11, in <module>
    from libs.financials_api_get import get_fundemental_data
ModuleNotFoundError: No module named 'libs'
[2023-12-05T22:46:39.388+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/fundamental_data_pipeline.py
[2023-12-05T22:46:39.405+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/fundamental_data_pipeline.py took 0.045 seconds
[2023-12-05T22:47:09.539+0000] {processor.py:157} INFO - Started process (PID=705) to work on /opt/airflow/dags/fundamental_data_pipeline.py
[2023-12-05T22:47:09.540+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/fundamental_data_pipeline.py for tasks to queue
[2023-12-05T22:47:09.542+0000] {logging_mixin.py:154} INFO - [2023-12-05T22:47:09.542+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/fundamental_data_pipeline.py
[2023-12-05T22:47:09.565+0000] {logging_mixin.py:154} INFO - [2023-12-05T22:47:09.559+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/fundamental_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/fundamental_data_pipeline.py", line 11, in <module>
    from libs.financials_api_get import get_fundemental_data
ModuleNotFoundError: No module named 'libs'
[2023-12-05T22:47:09.567+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/fundamental_data_pipeline.py
[2023-12-05T22:47:09.584+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/fundamental_data_pipeline.py took 0.048 seconds
[2023-12-05T22:47:39.713+0000] {processor.py:157} INFO - Started process (PID=713) to work on /opt/airflow/dags/fundamental_data_pipeline.py
[2023-12-05T22:47:39.714+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/fundamental_data_pipeline.py for tasks to queue
[2023-12-05T22:47:39.716+0000] {logging_mixin.py:154} INFO - [2023-12-05T22:47:39.716+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/fundamental_data_pipeline.py
[2023-12-05T22:47:39.740+0000] {logging_mixin.py:154} INFO - [2023-12-05T22:47:39.734+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/fundamental_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/fundamental_data_pipeline.py", line 11, in <module>
    from libs.financials_api_get import get_fundemental_data
ModuleNotFoundError: No module named 'libs'
[2023-12-05T22:47:39.742+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/fundamental_data_pipeline.py
[2023-12-05T22:47:39.759+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/fundamental_data_pipeline.py took 0.049 seconds
[2023-12-05T22:48:09.893+0000] {processor.py:157} INFO - Started process (PID=721) to work on /opt/airflow/dags/fundamental_data_pipeline.py
[2023-12-05T22:48:09.894+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/fundamental_data_pipeline.py for tasks to queue
[2023-12-05T22:48:09.896+0000] {logging_mixin.py:154} INFO - [2023-12-05T22:48:09.896+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/fundamental_data_pipeline.py
[2023-12-05T22:48:09.921+0000] {logging_mixin.py:154} INFO - [2023-12-05T22:48:09.917+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/fundamental_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/fundamental_data_pipeline.py", line 11, in <module>
    from libs.financials_api_get import get_fundemental_data
ModuleNotFoundError: No module named 'libs'
[2023-12-05T22:48:09.923+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/fundamental_data_pipeline.py
[2023-12-05T22:48:09.940+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/fundamental_data_pipeline.py took 0.050 seconds
[2023-12-05T22:48:40.092+0000] {processor.py:157} INFO - Started process (PID=729) to work on /opt/airflow/dags/fundamental_data_pipeline.py
[2023-12-05T22:48:40.093+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/fundamental_data_pipeline.py for tasks to queue
[2023-12-05T22:48:40.096+0000] {logging_mixin.py:154} INFO - [2023-12-05T22:48:40.095+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/fundamental_data_pipeline.py
[2023-12-05T22:48:40.121+0000] {logging_mixin.py:154} INFO - [2023-12-05T22:48:40.117+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/fundamental_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/fundamental_data_pipeline.py", line 11, in <module>
    from libs.financials_api_get import get_fundemental_data
ModuleNotFoundError: No module named 'libs'
[2023-12-05T22:48:40.122+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/fundamental_data_pipeline.py
[2023-12-05T22:48:40.139+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/fundamental_data_pipeline.py took 0.050 seconds
[2023-12-05T22:49:10.258+0000] {processor.py:157} INFO - Started process (PID=737) to work on /opt/airflow/dags/fundamental_data_pipeline.py
[2023-12-05T22:49:10.259+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/fundamental_data_pipeline.py for tasks to queue
[2023-12-05T22:49:10.266+0000] {logging_mixin.py:154} INFO - [2023-12-05T22:49:10.266+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/fundamental_data_pipeline.py
[2023-12-05T22:49:10.290+0000] {logging_mixin.py:154} INFO - [2023-12-05T22:49:10.285+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/fundamental_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/fundamental_data_pipeline.py", line 11, in <module>
    from libs.financials_api_get import get_fundemental_data
ModuleNotFoundError: No module named 'libs'
[2023-12-05T22:49:10.291+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/fundamental_data_pipeline.py
[2023-12-05T22:49:10.308+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/fundamental_data_pipeline.py took 0.054 seconds
[2023-12-05T22:49:40.443+0000] {processor.py:157} INFO - Started process (PID=745) to work on /opt/airflow/dags/fundamental_data_pipeline.py
[2023-12-05T22:49:40.444+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/fundamental_data_pipeline.py for tasks to queue
[2023-12-05T22:49:40.446+0000] {logging_mixin.py:154} INFO - [2023-12-05T22:49:40.446+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/fundamental_data_pipeline.py
[2023-12-05T22:49:40.472+0000] {logging_mixin.py:154} INFO - [2023-12-05T22:49:40.466+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/fundamental_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/fundamental_data_pipeline.py", line 11, in <module>
    from libs.financials_api_get import get_fundemental_data
ModuleNotFoundError: No module named 'libs'
[2023-12-05T22:49:40.473+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/fundamental_data_pipeline.py
[2023-12-05T22:49:40.491+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/fundamental_data_pipeline.py took 0.052 seconds
[2023-12-05T22:50:10.615+0000] {processor.py:157} INFO - Started process (PID=753) to work on /opt/airflow/dags/fundamental_data_pipeline.py
[2023-12-05T22:50:10.617+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/fundamental_data_pipeline.py for tasks to queue
[2023-12-05T22:50:10.619+0000] {logging_mixin.py:154} INFO - [2023-12-05T22:50:10.619+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/fundamental_data_pipeline.py
[2023-12-05T22:50:10.637+0000] {logging_mixin.py:154} INFO - [2023-12-05T22:50:10.634+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/fundamental_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/fundamental_data_pipeline.py", line 11, in <module>
    from libs.financials_api_get import get_fundemental_data
ModuleNotFoundError: No module named 'libs'
[2023-12-05T22:50:10.638+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/fundamental_data_pipeline.py
[2023-12-05T22:50:10.655+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/fundamental_data_pipeline.py took 0.042 seconds
[2023-12-05T22:50:40.803+0000] {processor.py:157} INFO - Started process (PID=761) to work on /opt/airflow/dags/fundamental_data_pipeline.py
[2023-12-05T22:50:40.803+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/fundamental_data_pipeline.py for tasks to queue
[2023-12-05T22:50:40.806+0000] {logging_mixin.py:154} INFO - [2023-12-05T22:50:40.806+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/fundamental_data_pipeline.py
[2023-12-05T22:50:40.827+0000] {logging_mixin.py:154} INFO - [2023-12-05T22:50:40.824+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/fundamental_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/fundamental_data_pipeline.py", line 11, in <module>
    from libs.financials_api_get import get_fundemental_data
ModuleNotFoundError: No module named 'libs'
[2023-12-05T22:50:40.829+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/fundamental_data_pipeline.py
[2023-12-05T22:50:40.846+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/fundamental_data_pipeline.py took 0.046 seconds
[2023-12-05T22:51:10.966+0000] {processor.py:157} INFO - Started process (PID=769) to work on /opt/airflow/dags/fundamental_data_pipeline.py
[2023-12-05T22:51:10.967+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/fundamental_data_pipeline.py for tasks to queue
[2023-12-05T22:51:10.970+0000] {logging_mixin.py:154} INFO - [2023-12-05T22:51:10.969+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/fundamental_data_pipeline.py
[2023-12-05T22:51:10.989+0000] {logging_mixin.py:154} INFO - [2023-12-05T22:51:10.985+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/fundamental_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/fundamental_data_pipeline.py", line 11, in <module>
    from libs.financials_api_get import get_fundemental_data
ModuleNotFoundError: No module named 'libs'
[2023-12-05T22:51:10.990+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/fundamental_data_pipeline.py
[2023-12-05T22:51:11.007+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/fundamental_data_pipeline.py took 0.044 seconds
[2023-12-05T22:51:41.158+0000] {processor.py:157} INFO - Started process (PID=777) to work on /opt/airflow/dags/fundamental_data_pipeline.py
[2023-12-05T22:51:41.160+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/fundamental_data_pipeline.py for tasks to queue
[2023-12-05T22:51:41.162+0000] {logging_mixin.py:154} INFO - [2023-12-05T22:51:41.162+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/fundamental_data_pipeline.py
[2023-12-05T22:51:41.183+0000] {logging_mixin.py:154} INFO - [2023-12-05T22:51:41.180+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/fundamental_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/fundamental_data_pipeline.py", line 11, in <module>
    from libs.financials_api_get import get_fundemental_data
ModuleNotFoundError: No module named 'libs'
[2023-12-05T22:51:41.184+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/fundamental_data_pipeline.py
[2023-12-05T22:51:41.206+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/fundamental_data_pipeline.py took 0.051 seconds
[2023-12-05T22:52:11.325+0000] {processor.py:157} INFO - Started process (PID=785) to work on /opt/airflow/dags/fundamental_data_pipeline.py
[2023-12-05T22:52:11.326+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/fundamental_data_pipeline.py for tasks to queue
[2023-12-05T22:52:11.328+0000] {logging_mixin.py:154} INFO - [2023-12-05T22:52:11.328+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/fundamental_data_pipeline.py
[2023-12-05T22:52:11.350+0000] {logging_mixin.py:154} INFO - [2023-12-05T22:52:11.346+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/fundamental_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/fundamental_data_pipeline.py", line 11, in <module>
    from libs.financials_api_get import get_fundemental_data
ModuleNotFoundError: No module named 'libs'
[2023-12-05T22:52:11.351+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/fundamental_data_pipeline.py
[2023-12-05T22:52:11.368+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/fundamental_data_pipeline.py took 0.046 seconds
[2023-12-05T22:52:41.522+0000] {processor.py:157} INFO - Started process (PID=793) to work on /opt/airflow/dags/fundamental_data_pipeline.py
[2023-12-05T22:52:41.523+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/fundamental_data_pipeline.py for tasks to queue
[2023-12-05T22:52:41.526+0000] {logging_mixin.py:154} INFO - [2023-12-05T22:52:41.525+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/fundamental_data_pipeline.py
[2023-12-05T22:52:41.550+0000] {logging_mixin.py:154} INFO - [2023-12-05T22:52:41.545+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/fundamental_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/fundamental_data_pipeline.py", line 11, in <module>
    from libs.financials_api_get import get_fundemental_data
ModuleNotFoundError: No module named 'libs'
[2023-12-05T22:52:41.552+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/fundamental_data_pipeline.py
[2023-12-05T22:52:41.569+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/fundamental_data_pipeline.py took 0.050 seconds
[2023-12-05T22:53:11.685+0000] {processor.py:157} INFO - Started process (PID=801) to work on /opt/airflow/dags/fundamental_data_pipeline.py
[2023-12-05T22:53:11.686+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/fundamental_data_pipeline.py for tasks to queue
[2023-12-05T22:53:11.688+0000] {logging_mixin.py:154} INFO - [2023-12-05T22:53:11.688+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/fundamental_data_pipeline.py
[2023-12-05T22:53:11.710+0000] {logging_mixin.py:154} INFO - [2023-12-05T22:53:11.706+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/fundamental_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/fundamental_data_pipeline.py", line 11, in <module>
    from libs.financials_api_get import get_fundemental_data
ModuleNotFoundError: No module named 'libs'
[2023-12-05T22:53:11.712+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/fundamental_data_pipeline.py
[2023-12-05T22:53:11.730+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/fundamental_data_pipeline.py took 0.048 seconds
[2023-12-05T22:53:41.907+0000] {processor.py:157} INFO - Started process (PID=809) to work on /opt/airflow/dags/fundamental_data_pipeline.py
[2023-12-05T22:53:41.909+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/fundamental_data_pipeline.py for tasks to queue
[2023-12-05T22:53:41.911+0000] {logging_mixin.py:154} INFO - [2023-12-05T22:53:41.911+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/fundamental_data_pipeline.py
[2023-12-05T22:53:41.936+0000] {logging_mixin.py:154} INFO - [2023-12-05T22:53:41.931+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/fundamental_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/fundamental_data_pipeline.py", line 11, in <module>
    from libs.financials_api_get import get_fundemental_data
ModuleNotFoundError: No module named 'libs'
[2023-12-05T22:53:41.937+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/fundamental_data_pipeline.py
[2023-12-05T22:53:41.955+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/fundamental_data_pipeline.py took 0.051 seconds
[2023-12-05T22:54:12.070+0000] {processor.py:157} INFO - Started process (PID=817) to work on /opt/airflow/dags/fundamental_data_pipeline.py
[2023-12-05T22:54:12.072+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/fundamental_data_pipeline.py for tasks to queue
[2023-12-05T22:54:12.074+0000] {logging_mixin.py:154} INFO - [2023-12-05T22:54:12.074+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/fundamental_data_pipeline.py
[2023-12-05T22:54:12.098+0000] {logging_mixin.py:154} INFO - [2023-12-05T22:54:12.094+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/fundamental_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/fundamental_data_pipeline.py", line 11, in <module>
    from libs.financials_api_get import get_fundemental_data
ModuleNotFoundError: No module named 'libs'
[2023-12-05T22:54:12.100+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/fundamental_data_pipeline.py
[2023-12-05T22:54:12.116+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/fundamental_data_pipeline.py took 0.049 seconds
[2023-12-05T22:54:42.263+0000] {processor.py:157} INFO - Started process (PID=825) to work on /opt/airflow/dags/fundamental_data_pipeline.py
[2023-12-05T22:54:42.263+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/fundamental_data_pipeline.py for tasks to queue
[2023-12-05T22:54:42.266+0000] {logging_mixin.py:154} INFO - [2023-12-05T22:54:42.266+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/fundamental_data_pipeline.py
[2023-12-05T22:54:42.286+0000] {logging_mixin.py:154} INFO - [2023-12-05T22:54:42.283+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/fundamental_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/fundamental_data_pipeline.py", line 11, in <module>
    from libs.financials_api_get import get_fundemental_data
ModuleNotFoundError: No module named 'libs'
[2023-12-05T22:54:42.288+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/fundamental_data_pipeline.py
[2023-12-05T22:54:42.306+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/fundamental_data_pipeline.py took 0.045 seconds
[2023-12-05T22:55:12.425+0000] {processor.py:157} INFO - Started process (PID=833) to work on /opt/airflow/dags/fundamental_data_pipeline.py
[2023-12-05T22:55:12.426+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/fundamental_data_pipeline.py for tasks to queue
[2023-12-05T22:55:12.429+0000] {logging_mixin.py:154} INFO - [2023-12-05T22:55:12.429+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/fundamental_data_pipeline.py
[2023-12-05T22:55:12.451+0000] {logging_mixin.py:154} INFO - [2023-12-05T22:55:12.447+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/fundamental_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/fundamental_data_pipeline.py", line 11, in <module>
    from libs.financials_api_get import get_fundemental_data
ModuleNotFoundError: No module named 'libs'
[2023-12-05T22:55:12.452+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/fundamental_data_pipeline.py
[2023-12-05T22:55:12.469+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/fundamental_data_pipeline.py took 0.047 seconds
[2023-12-05T22:55:42.597+0000] {processor.py:157} INFO - Started process (PID=841) to work on /opt/airflow/dags/fundamental_data_pipeline.py
[2023-12-05T22:55:42.598+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/fundamental_data_pipeline.py for tasks to queue
[2023-12-05T22:55:42.601+0000] {logging_mixin.py:154} INFO - [2023-12-05T22:55:42.601+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/fundamental_data_pipeline.py
[2023-12-05T22:55:42.621+0000] {logging_mixin.py:154} INFO - [2023-12-05T22:55:42.618+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/fundamental_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/fundamental_data_pipeline.py", line 11, in <module>
    from libs.financials_api_get import get_fundemental_data
ModuleNotFoundError: No module named 'libs'
[2023-12-05T22:55:42.622+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/fundamental_data_pipeline.py
[2023-12-05T22:55:42.640+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/fundamental_data_pipeline.py took 0.045 seconds
[2023-12-05T22:56:12.783+0000] {processor.py:157} INFO - Started process (PID=849) to work on /opt/airflow/dags/fundamental_data_pipeline.py
[2023-12-05T22:56:12.784+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/fundamental_data_pipeline.py for tasks to queue
[2023-12-05T22:56:12.786+0000] {logging_mixin.py:154} INFO - [2023-12-05T22:56:12.786+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/fundamental_data_pipeline.py
[2023-12-05T22:56:12.806+0000] {logging_mixin.py:154} INFO - [2023-12-05T22:56:12.802+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/fundamental_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/fundamental_data_pipeline.py", line 11, in <module>
    from libs.financials_api_get import get_fundemental_data
ModuleNotFoundError: No module named 'libs'
[2023-12-05T22:56:12.807+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/fundamental_data_pipeline.py
[2023-12-05T22:56:12.824+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/fundamental_data_pipeline.py took 0.044 seconds
[2023-12-05T22:56:42.950+0000] {processor.py:157} INFO - Started process (PID=857) to work on /opt/airflow/dags/fundamental_data_pipeline.py
[2023-12-05T22:56:42.951+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/fundamental_data_pipeline.py for tasks to queue
[2023-12-05T22:56:42.954+0000] {logging_mixin.py:154} INFO - [2023-12-05T22:56:42.954+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/fundamental_data_pipeline.py
[2023-12-05T22:56:42.972+0000] {logging_mixin.py:154} INFO - [2023-12-05T22:56:42.969+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/fundamental_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/fundamental_data_pipeline.py", line 11, in <module>
    from libs.financials_api_get import get_fundemental_data
ModuleNotFoundError: No module named 'libs'
[2023-12-05T22:56:42.973+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/fundamental_data_pipeline.py
[2023-12-05T22:56:42.990+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/fundamental_data_pipeline.py took 0.043 seconds
[2023-12-05T22:57:13.133+0000] {processor.py:157} INFO - Started process (PID=865) to work on /opt/airflow/dags/fundamental_data_pipeline.py
[2023-12-05T22:57:13.134+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/fundamental_data_pipeline.py for tasks to queue
[2023-12-05T22:57:13.136+0000] {logging_mixin.py:154} INFO - [2023-12-05T22:57:13.136+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/fundamental_data_pipeline.py
[2023-12-05T22:57:13.160+0000] {logging_mixin.py:154} INFO - [2023-12-05T22:57:13.155+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/fundamental_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/fundamental_data_pipeline.py", line 11, in <module>
    from libs.financials_api_get import get_fundemental_data
ModuleNotFoundError: No module named 'libs'
[2023-12-05T22:57:13.162+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/fundamental_data_pipeline.py
[2023-12-05T22:57:13.180+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/fundamental_data_pipeline.py took 0.050 seconds
[2023-12-05T22:57:43.298+0000] {processor.py:157} INFO - Started process (PID=873) to work on /opt/airflow/dags/fundamental_data_pipeline.py
[2023-12-05T22:57:43.299+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/fundamental_data_pipeline.py for tasks to queue
[2023-12-05T22:57:43.301+0000] {logging_mixin.py:154} INFO - [2023-12-05T22:57:43.301+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/fundamental_data_pipeline.py
[2023-12-05T22:57:43.324+0000] {logging_mixin.py:154} INFO - [2023-12-05T22:57:43.320+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/fundamental_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/fundamental_data_pipeline.py", line 11, in <module>
    from libs.financials_api_get import get_fundemental_data
ModuleNotFoundError: No module named 'libs'
[2023-12-05T22:57:43.325+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/fundamental_data_pipeline.py
[2023-12-05T22:57:43.343+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/fundamental_data_pipeline.py took 0.049 seconds
[2023-12-05T22:58:13.480+0000] {processor.py:157} INFO - Started process (PID=881) to work on /opt/airflow/dags/fundamental_data_pipeline.py
[2023-12-05T22:58:13.481+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/fundamental_data_pipeline.py for tasks to queue
[2023-12-05T22:58:13.483+0000] {logging_mixin.py:154} INFO - [2023-12-05T22:58:13.482+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/fundamental_data_pipeline.py
[2023-12-05T22:58:13.500+0000] {logging_mixin.py:154} INFO - [2023-12-05T22:58:13.498+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/fundamental_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/fundamental_data_pipeline.py", line 11, in <module>
    from libs.financials_api_get import get_fundemental_data
ModuleNotFoundError: No module named 'libs'
[2023-12-05T22:58:13.501+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/fundamental_data_pipeline.py
[2023-12-05T22:58:13.518+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/fundamental_data_pipeline.py took 0.042 seconds
[2023-12-05T22:58:43.685+0000] {processor.py:157} INFO - Started process (PID=889) to work on /opt/airflow/dags/fundamental_data_pipeline.py
[2023-12-05T22:58:43.686+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/fundamental_data_pipeline.py for tasks to queue
[2023-12-05T22:58:43.688+0000] {logging_mixin.py:154} INFO - [2023-12-05T22:58:43.688+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/fundamental_data_pipeline.py
[2023-12-05T22:58:43.711+0000] {logging_mixin.py:154} INFO - [2023-12-05T22:58:43.706+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/fundamental_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/fundamental_data_pipeline.py", line 11, in <module>
    from libs.financials_api_get import get_fundemental_data
ModuleNotFoundError: No module named 'libs'
[2023-12-05T22:58:43.712+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/fundamental_data_pipeline.py
[2023-12-05T22:58:43.729+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/fundamental_data_pipeline.py took 0.047 seconds
[2023-12-05T22:59:13.851+0000] {processor.py:157} INFO - Started process (PID=897) to work on /opt/airflow/dags/fundamental_data_pipeline.py
[2023-12-05T22:59:13.852+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/fundamental_data_pipeline.py for tasks to queue
[2023-12-05T22:59:13.855+0000] {logging_mixin.py:154} INFO - [2023-12-05T22:59:13.854+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/fundamental_data_pipeline.py
[2023-12-05T22:59:13.877+0000] {logging_mixin.py:154} INFO - [2023-12-05T22:59:13.873+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/fundamental_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/fundamental_data_pipeline.py", line 11, in <module>
    from libs.financials_api_get import get_fundemental_data
ModuleNotFoundError: No module named 'libs'
[2023-12-05T22:59:13.879+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/fundamental_data_pipeline.py
[2023-12-05T22:59:13.896+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/fundamental_data_pipeline.py took 0.048 seconds
[2023-12-05T22:59:44.041+0000] {processor.py:157} INFO - Started process (PID=905) to work on /opt/airflow/dags/fundamental_data_pipeline.py
[2023-12-05T22:59:44.042+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/fundamental_data_pipeline.py for tasks to queue
[2023-12-05T22:59:44.045+0000] {logging_mixin.py:154} INFO - [2023-12-05T22:59:44.044+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/fundamental_data_pipeline.py
[2023-12-05T22:59:44.067+0000] {logging_mixin.py:154} INFO - [2023-12-05T22:59:44.063+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/fundamental_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/fundamental_data_pipeline.py", line 11, in <module>
    from libs.financials_api_get import get_fundemental_data
ModuleNotFoundError: No module named 'libs'
[2023-12-05T22:59:44.069+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/fundamental_data_pipeline.py
[2023-12-05T22:59:44.085+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/fundamental_data_pipeline.py took 0.047 seconds
